AWSTemplateFormatVersion: "2010-09-09"

Description: cfn_nag demo template

Resources:
  EBSVolume:    
    Type: "AWS::EC2::Volume"
    Properties:
      Encrypted: true
      KmsKeyId: arn:aws:kms:us-east-1:002838516900:key/16a24bb3-6358-460e-88d1-8539d2f3451c
      AvailabilityZone: us-east-1a
      Size: 100
